-- 14. Find the total number of couriers handled by each employee
SELECT e.EmployeeID, e.Name, COUNT(c.CourierID) AS CouriersHandled
FROM Employee e
JOIN Courier c ON e.EmployeeID = c.CourierID
GROUP BY e.EmployeeID, e.Name

-- 15. Calculate the total revenue generated by each location
SELECT l.LocationID, l.LocationName, SUM(p.Amount) AS TotalRevenue
FROM Location l
JOIN Payment p ON l.LocationID = p.LocationID
GROUP BY l.LocationID, l.LocationName

-- 16. Find the total number of couriers delivered to each location
SELECT l.LocationID, l.LocationName, COUNT(c.CourierID) AS CouriersDelivered
FROM Location l
JOIN Courier c ON l.LocationID = c.CourierID
WHERE c.Status = 'Delivered'
GROUP BY l.LocationID, l.LocationName;

-- 17. Find the courier with the highest average delivery time
SELECT TOP 1 C.CourierID, AVG(DATEDIFF(DAY, P.PaymentDate, C.DeliveryDate)) AS AvgDeliveryTime
FROM Courier C
JOIN Payment P ON C.CourierID = P.CourierID
GROUP BY C.CourierID
ORDER BY AvgDeliveryTime DESC

-- 18. Find Locations with Total Payments Less Than a Certain Amount
SELECT L.LocationID, L.LocationName, SUM(P.Amount) AS TotalPayments
FROM Location L
JOIN Payment P ON L.LocationID = P.LocationID
GROUP BY L.LocationID, L.LocationName
HAVING SUM(P.Amount) < 1000;

-- 19. Calculate Total Payments per Location
SELECT L.LocationID, L.LocationName, SUM(P.Amount) AS TotalPayments
FROM Location L
JOIN Payment P ON L.LocationID = P.LocationID
GROUP BY L.LocationID, L.LocationName;

-- 20. Retrieve couriers who have received payments totaling more than $1000 in a specific location (LocationID = X)
SELECT C.CourierID, SUM(P.Amount) AS TotalPayments
FROM Courier C
JOIN Payment P ON C.CourierID = P.CourierID
WHERE P.LocationID = 1
GROUP BY C.CourierID
HAVING SUM(P.Amount) > 1000;

-- 21. Retrieve couriers who have received payments totaling more than $1000 after a certain date (PaymentDate > 'YYYY-MM-DD')
SELECT C.CourierID, SUM(P.Amount) AS TotalPayments
FROM Courier C
JOIN Payment P ON C.CourierID = P.CourierID
WHERE P.PaymentDate > '2025-03-15'
GROUP BY C.CourierID
HAVING SUM(P.Amount) > 1000;

-- 22. Retrieve locations where the total amount received is more than $5000 before a certain date (PaymentDate > 'YYYY-MM-DD')
SELECT L.LocationID, L.LocationName, SUM(P.Amount) AS TotalPayments
FROM Location L
JOIN Payment P ON L.LocationID = P.LocationID
WHERE P.PaymentDate < '2025-03-20'
GROUP BY L.LocationID, L.LocationName
HAVING SUM(P.Amount) > 5000;


