-- 1. Write an SQL query to retrieve a list of all orders along with customer information (e.g., customer name) for each order.
SELECT o.OrderID, o.OrderDate, c.FirstName 
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID;

-- 2. Write an SQL query to find the total revenue generated by each electronic gadget product. Include the product name and the total revenue.
SELECT p.ProductName, SUM(od.Quantity * p.Price) AS TotalRevenue
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName;

-- 3. Write an SQL query to list all customers who have made at least one purchase. Include their names and contact information.
SELECT DISTINCT c.FirstName , c.Phone, c.Email
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID;

-- 4. Write an SQL query to find the most popular electronic gadget, which is the one with the highest total quantity ordered. Include the product name and the total quantity ordered.
SELECT TOP 1 p.ProductName, SUM(od.Quantity) AS TotalQuantityOrdered
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName

-- 5. Write an SQL query to retrieve a list of electronic gadgets along with their corresponding categories.
SELECT ProductName from Products

-- 6. Write an SQL query to calculate the average order value for each customer. Include the customer's name and their average order value.
SELECT c.FirstName, AVG(od.Quantity * p.Price) AS AverageValue
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY c. FirstName;

-- 7. Write an SQL query to find the order with the highest total revenue. Include the order ID, customer information, and the total revenue.
SELECT o.OrderID, c.FirstName, c.Phone, SUM(od.Quantity * p.Price) AS TotalRevenue
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY o.OrderID, c.FirstName, c.Phone

-- 8. Write an SQL query to list electronic gadgets and the number of times each product has been ordered.
SELECT p.ProductName, COUNT(od.OrderID) AS OrderCount
FROM Products p
JOIN OrderDetails od ON p.ProductID = od.ProductID
GROUP BY p.ProductName

-- 9. Write an SQL query to find customers who have purchased a specific electronic gadget product. Allow users to input the product name as a parameter.
SELECT c.Firstname, p.Productname
FROM Customers c
JOIN Products p ON c.CustomerID= p.ProductID

-- 10. Write an SQL query to calculate the total revenue generated by all orders placed within a specific time period. Allow users to input the start and end dates as parameters.
SELECT SUM(od.Quantity * p.Price) AS TotalRevenue
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
WHERE o.OrderDate BETWEEN '2024-03-05' AND '2024-03-15'
